<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="EternalfestDesktop.Tests" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EternalfestDesktop.Application\EternalfestDesktop.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Quests\quests.json" LogicalName="EternalfestDesktop.Infrastructure.Quests.quests.json" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\assets\flash\**\*" LinkBase="flash" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
  </ItemGroup>
</Project>
